apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      app: tickets
  replicas: 1
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: {{.Values.tickets.image}}
          resources:
            requests:
              memory: 300Mi
              cpu: 50m
          readinessProbe:
            httpGet:
              path: {{.Values.tickets.readinessProbe}}
              port: 4000
          env:
          {{- include "mongoURI" . | indent 12 -}}
            - name: RABBITMQ_CONNECTION
              value: {{.Values.tickets.env.RABBITMQ_CONNECTION}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svc
spec:
  selector:
    app: tickets
  ports:
    - port: 4000
      targetPort: 4000